version: "3.9"

services:
    django:
        container_name: django
        env_file: django.env
        build: .
        volumes:
            - ./chess:/Online-Chess/chess
            - ./db.sqlite3:/Online-Chess/db.sqlite3
            - static:/nginx-static
        ports:
            - "8000:8000"
        links:
            - redis

    daphne:
        container_name: daphne
        env_file: django.env
        build: .
        volumes:
            - ./chess:/Online-Chess/chess
            - ./db.sqlite3:/Online-Chess/db.sqlite3
        entrypoint: /Online-Chess/daphne/entrypoint.sh
        ports:
            - "8001:8001"
        depends_on:
            - redis
        links:
            - redis

    worker:
        container_name: worker
        env_file: django.env
        build: .
        volumes:
            - ./chess:/Online-Chess/chess
            - ./db.sqlite3:/Online-Chess/db.sqlite3
        entrypoint: /Online-Chess/worker/entrypoint.sh
        depends_on:
            - redis
            - daphne
        links:
            - redis

    redis:
        image: redis
        ports:
            - "6379:6379"

    nginx:
        build: ./nginx
        volumes:
            - static:/static
        ports:
            - "80:80"
        depends_on:
            - django
            - daphne

volumes:
    static:
