version: "3.9"

services:
    django:
        container_name: django
        build: .
        volumes:
            - .:/Online-Chess
        ports:
            - "80:8000"
        command: gunicorn -b :8000 --workers 3 --pythonpath ./chess chess.wsgi
        links:
            - redis

    redis:
        image: redis
        ports:
            - "6379:6379"