version: "3.9"

services:
    django:
        container_name: django
        build: .
        volumes:
            - .:/Online-Chess
        ports:
            - "8000:8000"
        command: python3 chess/manage.py runserver 0.0.0.0:8000
        links:
            - redis

    redis:
        image: redis
        ports:
            - "6379:6379"