# Generated by Django 3.2 on 2021-04-21 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStarted', models.DateTimeField(default=django.utils.timezone.now)),
                ('whitesTurn', models.BooleanField(default=True)),
                ('check', models.BooleanField(default=False)),
                ('winner', models.CharField(default='0', max_length=1)),
                ('board', models.CharField(default='RNBQKBNRPPPPPPPP00000000000000000000000000000000pppppppprnbqkbnr', max_length=64)),
                ('moves', models.TextField(blank=True)),
                ('enPassant', models.IntegerField(default=-1)),
                ('castle', models.IntegerField(default=15)),
                ('captured', models.CharField(blank=True, max_length=30)),
                ('wAttacksTop', models.IntegerField(default=0)),
                ('wAttacksBottom', models.IntegerField(default=0)),
                ('bAttacksTop', models.IntegerField(default=0)),
                ('bAttacksBottom', models.IntegerField(default=0)),
                ('kAttacker1', models.IntegerField(default=-1)),
                ('kAttacker2', models.IntegerField(default=-1)),
            ],
        ),
    ]
