# Generated by Django 3.1.7 on 2021-03-23 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStarted', models.DateTimeField(default=django.utils.timezone.now)),
                ('whitesTurn', models.BooleanField(default=True)),
                ('checkMate', models.BooleanField(default=False)),
                ('board', models.CharField(default='        RNBQKBNR        PPPPPPPP        00000000        00000000        00000000        00000000        pppppppp        rnbqkbnr', max_length=64)),
                ('moves', models.TextField()),
            ],
        ),
    ]
