# Generated by Django 3.1.7 on 2021-03-17 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgame',
            name='blackUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blackUserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedgame',
            name='whiteUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whiteUserId', to=settings.AUTH_USER_MODEL),
        ),
    ]
