# Generated by Django 3.2 on 2021-04-21 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='blackUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blackUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='whiteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whiteUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
