# Generated by Django 3.1.7 on 2021-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210323_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='board',
            field=models.CharField(default='RNBQKBNRPPPPPPPP00000000000000000000000000000000pppppppprnbqkbnr', max_length=64),
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='moves',
            field=models.TextField(blank=True),
        ),
    ]
