# Generated by Django 3.2 on 2021-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='promos',
            field=models.TextField(blank=True),
        ),
    ]
