# Generated by Django 3.1.7 on 2021-03-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210317_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitesTurn', models.BooleanField()),
                ('board', models.CharField(max_length=64)),
            ],
        ),
    ]
