# Generated by Django 3.2 on 2021-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameboard_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='enPassantIndex',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='moveCount',
            field=models.IntegerField(default=0),
        ),
    ]
