# Generated by Django 3.1.7 on 2021-03-26 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210325_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameboard',
            name='blackUserId',
        ),
        migrations.RemoveField(
            model_name='gameboard',
            name='whiteUserId',
        ),
        migrations.AddField(
            model_name='gameboard',
            name='blackUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='blackUser', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameboard',
            name='whiteUser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='whiteUser', to='users.user'),
            preserve_default=False,
        ),
    ]
