# Generated by Django 3.1.7 on 2021-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='board',
            field=models.CharField(default='        RNBQKBNR        PPPPPPPP        00000000        00000000        00000000        00000000        pppppppp        rnbqkbnr', max_length=64),
        ),
    ]
