# Generated by Django 3.1.7 on 2021-03-19 13:06

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210318_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='blackUserId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='blackUserId', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameboard',
            name='moves',
            field=models.TextField(default=12312),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameboard',
            name='timeStarted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='whiteUserId',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='whiteUserId', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='whitesTurn',
            field=models.BooleanField(default=api.models.GameBoard.flipCoin),
        ),
        migrations.DeleteModel(
            name='SavedGame',
        ),
    ]
