# Generated by Django 3.1.7 on 2021-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210326_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='castle',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='enPassant',
            field=models.IntegerField(default=-1),
        ),
    ]
