# Generated by Django 3.1.7 on 2021-03-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210319_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='whitesTurn',
            field=models.BooleanField(default=True),
        ),
    ]
