# Generated by Django 3.1.7 on 2021-04-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210405_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='captured',
            field=models.CharField(blank=True, max_length=29),
        ),
    ]
