# Generated by Django 3.1.7 on 2021-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210406_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='bAttacksBottom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='bAttacksTop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='wAttacksBottom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='wAttacksTop',
            field=models.IntegerField(default=0),
        ),
    ]
