# Generated by Django 3.1.7 on 2021-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210407_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='kAttackersBottom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='kAttackersTop',
            field=models.IntegerField(default=0),
        ),
    ]
