# Generated by Django 3.1.7 on 2021-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210408_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameboard',
            name='kAttackersBottom',
        ),
        migrations.RemoveField(
            model_name='gameboard',
            name='kAttackersTop',
        ),
        migrations.AddField(
            model_name='gameboard',
            name='kAttacker1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='kAttacker2',
            field=models.IntegerField(default=-1),
        ),
    ]
